name: crypto_icons_flutter
description: A new Flutter package project.
version: 0.0.1
homepage: https://github.com/codesniper9315/crypto_icons_flutter

environment:
  sdk: '>=3.1.5 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  enum_to_string: ^2.0.1
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:

  assets:
    - assets/black/
    - assets/color/
    - assets/white/
